//
//  UIColor+MBAdditions.h
//
//  Generated by Zeplin on 6/29/17.
//  Copyright (c) 2017 MicroBlink. All rights reserved.
//

#import <UIKit/UIKit.h>

@interface UIColor (MBAdditions)

+ (nonnull UIColor *)MB_slateGreyColor;

+ (nonnull UIColor *)MB_darkSkyBlueColor;

+ (nonnull UIColor *)MB_purpleyGreyColor;

+ (nonnull UIColor *)MB_shadowColor;

@end
