//
//  UIColor+MBAdditions.h
//
//  Generated by Zeplin on 6/29/17.
//  Copyright (c) 2017 MicroBlink. All rights reserved. 
//

#import <UIKit/UIKit.h>

@interface UIColor (MBAdditions)

+ (UIColor *)MB_emeraldColor;
+ (UIColor *)MB_slateGreyColor;
+ (UIColor *)MB_purpleyGreyColor;
+ (UIColor *)MB_shadowColor;

@end
