{"metadata":{"roleHeading":"Framework","modules":[{"name":"BlinkIDUX"}],"role":"collection","externalID":"BlinkIDUX","title":"BlinkIDUX","symbolKind":"module"},"schemaVersion":{"major":0,"patch":0,"minor":3},"topicSections":[{"identifiers":["doc:\/\/com.microblink.BlinkIDUX\/documentation\/BlinkIDUX\/BlinkIDAnalyzer","doc:\/\/com.microblink.BlinkIDUX\/documentation\/BlinkIDUX\/BlinkIDEventStream","doc:\/\/com.microblink.BlinkIDUX\/documentation\/BlinkIDUX\/BlinkIDTheme","doc:\/\/com.microblink.BlinkIDUX\/documentation\/BlinkIDUX\/BlinkIDUXModel","doc:\/\/com.microblink.BlinkIDUX\/documentation\/BlinkIDUX\/Camera","doc:\/\/com.microblink.BlinkIDUX\/documentation\/BlinkIDUX\/NetworkMonitor","doc:\/\/com.microblink.BlinkIDUX\/documentation\/BlinkIDUX\/SampleBuffer","doc:\/\/com.microblink.BlinkIDUX\/documentation\/BlinkIDUX\/ScanningViewModel"],"anchor":"Classes","generated":true,"title":"Classes"},{"anchor":"Protocols","generated":true,"identifiers":["doc:\/\/com.microblink.BlinkIDUX\/documentation\/BlinkIDUX\/AlertTypeProtocol","doc:\/\/com.microblink.BlinkIDUX\/documentation\/BlinkIDUX\/BlinkIDClassFilter","doc:\/\/com.microblink.BlinkIDUX\/documentation\/BlinkIDUX\/CameraFrameAnalyzer","doc:\/\/com.microblink.BlinkIDUX\/documentation\/BlinkIDUX\/CameraModel","doc:\/\/com.microblink.BlinkIDUX\/documentation\/BlinkIDUX\/EventStream","doc:\/\/com.microblink.BlinkIDUX\/documentation\/BlinkIDUX\/PreviewSource","doc:\/\/com.microblink.BlinkIDUX\/documentation\/BlinkIDUX\/PreviewTarget","doc:\/\/com.microblink.BlinkIDUX\/documentation\/BlinkIDUX\/ScanningResultProtocol","doc:\/\/com.microblink.BlinkIDUX\/documentation\/BlinkIDUX\/UXThemeProtocol"],"title":"Protocols"},{"title":"Structures","anchor":"Structures","generated":true,"identifiers":["doc:\/\/com.microblink.BlinkIDUX\/documentation\/BlinkIDUX\/BlinkIDResultState","doc:\/\/com.microblink.BlinkIDUX\/documentation\/BlinkIDUX\/BlinkIDUXView","doc:\/\/com.microblink.BlinkIDUX\/documentation\/BlinkIDUX\/CameraPreview","doc:\/\/com.microblink.BlinkIDUX\/documentation\/BlinkIDUX\/CameraView","doc:\/\/com.microblink.BlinkIDUX\/documentation\/BlinkIDUX\/NoInternetView"]},{"anchor":"Enumerations","title":"Enumerations","generated":true,"identifiers":["doc:\/\/com.microblink.BlinkIDUX\/documentation\/BlinkIDUX\/BlinkIDScanningAlertType","doc:\/\/com.microblink.BlinkIDUX\/documentation\/BlinkIDUX\/CameraStatus","doc:\/\/com.microblink.BlinkIDUX\/documentation\/BlinkIDUX\/CaptureActivity","doc:\/\/com.microblink.BlinkIDUX\/documentation\/BlinkIDUX\/CaptureMode","doc:\/\/com.microblink.BlinkIDUX\/documentation\/BlinkIDUX\/DocumentSide","doc:\/\/com.microblink.BlinkIDUX\/documentation\/BlinkIDUX\/MicroblinkColor","doc:\/\/com.microblink.BlinkIDUX\/documentation\/BlinkIDUX\/ReticleState","doc:\/\/com.microblink.BlinkIDUX\/documentation\/BlinkIDUX\/ScanningResult","doc:\/\/com.microblink.BlinkIDUX\/documentation\/BlinkIDUX\/UIEvent"]},{"title":"Extended Modules","generated":true,"identifiers":["doc:\/\/com.microblink.BlinkIDUX\/documentation\/BlinkIDUX\/AVFoundation","doc:\/\/com.microblink.BlinkIDUX\/documentation\/BlinkIDUX\/SwiftUICore"],"anchor":"Extended-Modules"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.microblink.BlinkIDUX\/documentation\/BlinkIDUX"},"sections":[],"kind":"symbol","variants":[{"paths":["\/documentation\/blinkidux"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/blinkidux"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[[]]},"references":{"doc://com.microblink.BlinkIDUX/documentation/BlinkIDUX/ScanningViewModel":{"url":"\/documentation\/blinkidux\/scanningviewmodel","title":"ScanningViewModel","kind":"symbol","type":"topic","identifier":"doc:\/\/com.microblink.BlinkIDUX\/documentation\/BlinkIDUX\/ScanningViewModel","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ScanningViewModel"}],"abstract":[{"text":"Base class containing common scanning functionality","type":"text"}],"navigatorTitle":[{"text":"ScanningViewModel","kind":"identifier"}]},"doc://com.microblink.BlinkIDUX/documentation/BlinkIDUX/PreviewTarget":{"identifier":"doc:\/\/com.microblink.BlinkIDUX\/documentation\/BlinkIDUX\/PreviewTarget","type":"topic","navigatorTitle":[{"text":"PreviewTarget","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/blinkidux\/previewtarget","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"PreviewTarget","kind":"identifier"}],"role":"symbol","abstract":[{"type":"text","text":"A protocol that passes the app’s capture session to the "},{"type":"codeVoice","code":"CameraPreview"},{"text":" view.","type":"text"}],"title":"PreviewTarget"},"doc://com.microblink.BlinkIDUX/documentation/BlinkIDUX/BlinkIDAnalyzer":{"identifier":"doc:\/\/com.microblink.BlinkIDUX\/documentation\/BlinkIDUX\/BlinkIDAnalyzer","title":"BlinkIDAnalyzer","type":"topic","abstract":[],"role":"symbol","kind":"symbol","url":"\/documentation\/blinkidux\/blinkidanalyzer","navigatorTitle":[{"kind":"identifier","text":"BlinkIDAnalyzer"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"BlinkIDAnalyzer"}]},"doc://com.microblink.BlinkIDUX/documentation/BlinkIDUX/SwiftUICore":{"abstract":[],"url":"\/documentation\/blinkidux\/swiftuicore","kind":"symbol","role":"collection","identifier":"doc:\/\/com.microblink.BlinkIDUX\/documentation\/BlinkIDUX\/SwiftUICore","type":"topic","title":"SwiftUICore"},"doc://com.microblink.BlinkIDUX/documentation/BlinkIDUX/CameraFrameAnalyzer":{"navigatorTitle":[{"text":"CameraFrameAnalyzer","kind":"identifier"}],"title":"CameraFrameAnalyzer","abstract":[{"text":"A protocol that represents the interface to the features of Microblink’s analyzer.","type":"text"}],"kind":"symbol","type":"topic","role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CameraFrameAnalyzer","kind":"identifier"}],"identifier":"doc:\/\/com.microblink.BlinkIDUX\/documentation\/BlinkIDUX\/CameraFrameAnalyzer","url":"\/documentation\/blinkidux\/cameraframeanalyzer"},"doc://com.microblink.BlinkIDUX/documentation/BlinkIDUX/AlertTypeProtocol":{"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"text":"AlertTypeProtocol","kind":"identifier"}],"title":"AlertTypeProtocol","navigatorTitle":[{"text":"AlertTypeProtocol","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/com.microblink.BlinkIDUX\/documentation\/BlinkIDUX\/AlertTypeProtocol","url":"\/documentation\/blinkidux\/alerttypeprotocol","kind":"symbol","abstract":[],"role":"symbol"},"doc://com.microblink.BlinkIDUX/documentation/BlinkIDUX/BlinkIDScanningAlertType":{"identifier":"doc:\/\/com.microblink.BlinkIDUX\/documentation\/BlinkIDUX\/BlinkIDScanningAlertType","type":"topic","url":"\/documentation\/blinkidux\/blinkidscanningalerttype","title":"BlinkIDScanningAlertType","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"BlinkIDScanningAlertType"}],"role":"symbol","abstract":[{"type":"text","text":"Scanning alert type"}],"fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"BlinkIDScanningAlertType","kind":"identifier"}]},"doc://com.microblink.BlinkIDUX/documentation/BlinkIDUX/NoInternetView":{"url":"\/documentation\/blinkidux\/nointernetview","abstract":[],"type":"topic","navigatorTitle":[{"text":"NoInternetView","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/com.microblink.BlinkIDUX\/documentation\/BlinkIDUX\/NoInternetView","role":"symbol","fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"kind":"identifier","text":"NoInternetView"}],"title":"NoInternetView"},"doc://com.microblink.BlinkIDUX/documentation/BlinkIDUX/BlinkIDUXView":{"title":"BlinkIDUXView","type":"topic","role":"symbol","kind":"symbol","identifier":"doc:\/\/com.microblink.BlinkIDUX\/documentation\/BlinkIDUX\/BlinkIDUXView","navigatorTitle":[{"text":"BlinkIDUXView","kind":"identifier"}],"url":"\/documentation\/blinkidux\/blinkiduxview","abstract":[{"text":"Main scanning view.","type":"text"},{"text":" ","type":"text"},{"text":"This view consists of ","type":"text"},{"code":"CameraView","type":"codeVoice"},{"text":" and ","type":"text"},{"code":"Reticle","type":"codeVoice"},{"text":".","type":"text"}],"fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"text":"BlinkIDUXView","kind":"identifier"}]},"doc://com.microblink.BlinkIDUX/documentation/BlinkIDUX/BlinkIDTheme":{"title":"BlinkIDTheme","type":"topic","url":"\/documentation\/blinkidux\/blinkidtheme","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"BlinkIDTheme"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"BlinkIDTheme"}],"abstract":[],"identifier":"doc:\/\/com.microblink.BlinkIDUX\/documentation\/BlinkIDUX\/BlinkIDTheme"},"doc://com.microblink.BlinkIDUX/documentation/BlinkIDUX/CameraStatus":{"abstract":[{"text":"An enumeration that describes the current status of the camera.","type":"text"}],"kind":"symbol","type":"topic","title":"CameraStatus","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"CameraStatus"}],"url":"\/documentation\/blinkidux\/camerastatus","navigatorTitle":[{"kind":"identifier","text":"CameraStatus"}],"identifier":"doc:\/\/com.microblink.BlinkIDUX\/documentation\/BlinkIDUX\/CameraStatus"},"doc://com.microblink.BlinkIDUX/documentation/BlinkIDUX/NetworkMonitor":{"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"NetworkMonitor","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/blinkidux\/networkmonitor","title":"NetworkMonitor","identifier":"doc:\/\/com.microblink.BlinkIDUX\/documentation\/BlinkIDUX\/NetworkMonitor","type":"topic","abstract":[{"text":"Monitors network connectivity status using NWPathMonitor.","type":"text"}],"role":"symbol","navigatorTitle":[{"text":"NetworkMonitor","kind":"identifier"}]},"doc://com.microblink.BlinkIDUX/documentation/BlinkIDUX/UXThemeProtocol":{"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"UXThemeProtocol","kind":"identifier"}],"navigatorTitle":[{"text":"UXThemeProtocol","kind":"identifier"}],"title":"UXThemeProtocol","kind":"symbol","role":"symbol","identifier":"doc:\/\/com.microblink.BlinkIDUX\/documentation\/BlinkIDUX\/UXThemeProtocol","url":"\/documentation\/blinkidux\/uxthemeprotocol","type":"topic","abstract":[]},"doc://com.microblink.BlinkIDUX/documentation/BlinkIDUX/PreviewSource":{"identifier":"doc:\/\/com.microblink.BlinkIDUX\/documentation\/BlinkIDUX\/PreviewSource","type":"topic","navigatorTitle":[{"text":"PreviewSource","kind":"identifier"}],"url":"\/documentation\/blinkidux\/previewsource","kind":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PreviewSource"}],"role":"symbol","title":"PreviewSource","abstract":[{"text":"A protocol that enables a preview source to connect to a preview target.","type":"text"}]},"doc://com.microblink.BlinkIDUX/documentation/BlinkIDUX/BlinkIDResultState":{"identifier":"doc:\/\/com.microblink.BlinkIDUX\/documentation\/BlinkIDUX\/BlinkIDResultState","type":"topic","url":"\/documentation\/blinkidux\/blinkidresultstate","navigatorTitle":[{"kind":"identifier","text":"BlinkIDResultState"}],"abstract":[],"title":"BlinkIDResultState","kind":"symbol","fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"text":"BlinkIDResultState","kind":"identifier"}],"role":"symbol"},"doc://com.microblink.BlinkIDUX/documentation/BlinkIDUX/ScanningResult":{"navigatorTitle":[{"kind":"identifier","text":"ScanningResult"}],"kind":"symbol","abstract":[{"type":"text","text":"Result of a document scanning session."}],"title":"ScanningResult","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"ScanningResult","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/com.microblink.BlinkIDUX\/documentation\/BlinkIDUX\/ScanningResult","role":"symbol","url":"\/documentation\/blinkidux\/scanningresult"},"doc://com.microblink.BlinkIDUX/documentation/BlinkIDUX/BlinkIDUXModel":{"type":"topic","abstract":[{"text":"A view model that manages the user experience flow for document scanning.","type":"text"},{"type":"text","text":" "},{"text":"Handles camera preview, document detection, user guidance, and scanning state transitions.","type":"text"}],"kind":"symbol","identifier":"doc:\/\/com.microblink.BlinkIDUX\/documentation\/BlinkIDUX\/BlinkIDUXModel","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"BlinkIDUXModel"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"BlinkIDUXModel"}],"url":"\/documentation\/blinkidux\/blinkiduxmodel","title":"BlinkIDUXModel"},"doc://com.microblink.BlinkIDUX/documentation/BlinkIDUX/UIEvent":{"kind":"symbol","url":"\/documentation\/blinkidux\/uievent","type":"topic","navigatorTitle":[{"text":"UIEvent","kind":"identifier"}],"role":"symbol","abstract":[{"text":"Events that represent different states and user guidance during document scanning.","type":"text"}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"UIEvent","kind":"identifier"}],"title":"UIEvent","identifier":"doc:\/\/com.microblink.BlinkIDUX\/documentation\/BlinkIDUX\/UIEvent"},"doc://com.microblink.BlinkIDUX/documentation/BlinkIDUX/Camera":{"role":"symbol","type":"topic","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"Camera","kind":"identifier"}],"title":"Camera","url":"\/documentation\/blinkidux\/camera","abstract":[{"type":"text","text":"An object that provides the interface to the features of the camera."}],"identifier":"doc:\/\/com.microblink.BlinkIDUX\/documentation\/BlinkIDUX\/Camera","navigatorTitle":[{"text":"Camera","kind":"identifier"}]},"doc://com.microblink.BlinkIDUX/documentation/BlinkIDUX/CameraModel":{"kind":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"CameraModel"}],"role":"symbol","navigatorTitle":[{"text":"CameraModel","kind":"identifier"}],"type":"topic","url":"\/documentation\/blinkidux\/cameramodel","title":"CameraModel","abstract":[{"type":"text","text":"A protocol that represents the model for the camera."}],"identifier":"doc:\/\/com.microblink.BlinkIDUX\/documentation\/BlinkIDUX\/CameraModel"},"doc://com.microblink.BlinkIDUX/documentation/BlinkIDUX/AVFoundation":{"kind":"symbol","url":"\/documentation\/blinkidux\/avfoundation","title":"AVFoundation","identifier":"doc:\/\/com.microblink.BlinkIDUX\/documentation\/BlinkIDUX\/AVFoundation","type":"topic","abstract":[],"role":"collection"},"doc://com.microblink.BlinkIDUX/documentation/BlinkIDUX/ReticleState":{"identifier":"doc:\/\/com.microblink.BlinkIDUX\/documentation\/BlinkIDUX\/ReticleState","abstract":[],"type":"topic","role":"symbol","kind":"symbol","url":"\/documentation\/blinkidux\/reticlestate","title":"ReticleState","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"ReticleState","kind":"identifier"}],"navigatorTitle":[{"text":"ReticleState","kind":"identifier"}]},"doc://com.microblink.BlinkIDUX/documentation/BlinkIDUX/BlinkIDEventStream":{"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"BlinkIDEventStream"}],"type":"topic","navigatorTitle":[{"text":"BlinkIDEventStream","kind":"identifier"}],"title":"BlinkIDEventStream","role":"symbol","identifier":"doc:\/\/com.microblink.BlinkIDUX\/documentation\/BlinkIDUX\/BlinkIDEventStream","kind":"symbol","abstract":[],"url":"\/documentation\/blinkidux\/blinkideventstream"},"doc://com.microblink.BlinkIDUX/documentation/BlinkIDUX/EventStream":{"kind":"symbol","navigatorTitle":[{"text":"EventStream","kind":"identifier"}],"title":"EventStream","role":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"EventStream"}],"type":"topic","identifier":"doc:\/\/com.microblink.BlinkIDUX\/documentation\/BlinkIDUX\/EventStream","url":"\/documentation\/blinkidux\/eventstream","abstract":[{"text":"Protocol for streaming events during document processing.","type":"text"}]},"doc://com.microblink.BlinkIDUX/documentation/BlinkIDUX/CameraView":{"navigatorTitle":[{"text":"CameraView","kind":"identifier"}],"type":"topic","kind":"symbol","title":"CameraView","role":"symbol","url":"\/documentation\/blinkidux\/cameraview","identifier":"doc:\/\/com.microblink.BlinkIDUX\/documentation\/BlinkIDUX\/CameraView","abstract":[],"fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"text":"CameraView","kind":"identifier"}]},"doc://com.microblink.BlinkIDUX/documentation/BlinkIDUX/ScanningResultProtocol":{"identifier":"doc:\/\/com.microblink.BlinkIDUX\/documentation\/BlinkIDUX\/ScanningResultProtocol","type":"topic","navigatorTitle":[{"text":"ScanningResultProtocol","kind":"identifier"}],"url":"\/documentation\/blinkidux\/scanningresultprotocol","kind":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"ScanningResultProtocol","kind":"identifier"}],"role":"symbol","title":"ScanningResultProtocol","abstract":[]},"doc://com.microblink.BlinkIDUX/documentation/BlinkIDUX/CameraPreview":{"type":"topic","fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"kind":"identifier","text":"CameraPreview"}],"navigatorTitle":[{"text":"CameraPreview","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/blinkidux\/camerapreview","identifier":"doc:\/\/com.microblink.BlinkIDUX\/documentation\/BlinkIDUX\/CameraPreview","title":"CameraPreview","abstract":[],"role":"symbol"},"doc://com.microblink.BlinkIDUX/documentation/BlinkIDUX/BlinkIDUXVersionNumber":{"abstract":[{"type":"text","text":"Project version number for SwiftTest."}],"identifier":"doc:\/\/com.microblink.BlinkIDUX\/documentation\/BlinkIDUX\/BlinkIDUXVersionNumber","type":"topic","url":"\/documentation\/blinkidux\/blinkiduxversionnumber","title":"BlinkIDUXVersionNumber","fragments":[{"kind":"identifier","text":"BlinkIDUXVersionNumber"}],"role":"symbol","kind":"symbol"},"doc://com.microblink.BlinkIDUX/documentation/BlinkIDUX/BlinkIDUXVersionString":{"url":"\/documentation\/blinkidux\/blinkiduxversionstring","fragments":[{"kind":"identifier","text":"BlinkIDUXVersionString"}],"type":"topic","title":"BlinkIDUXVersionString","abstract":[{"text":"Project version string for SwiftTest.","type":"text"}],"kind":"symbol","role":"symbol","identifier":"doc:\/\/com.microblink.BlinkIDUX\/documentation\/BlinkIDUX\/BlinkIDUXVersionString"},"doc://com.microblink.BlinkIDUX/documentation/BlinkIDUX/CaptureMode":{"identifier":"doc:\/\/com.microblink.BlinkIDUX\/documentation\/BlinkIDUX\/CaptureMode","url":"\/documentation\/blinkidux\/capturemode","navigatorTitle":[{"text":"CaptureMode","kind":"identifier"}],"role":"symbol","type":"topic","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CaptureMode","kind":"identifier"}],"kind":"symbol","title":"CaptureMode","abstract":[{"text":"An enumeration of the capture modes that the camera supports.","type":"text"}]},"doc://com.microblink.BlinkIDUX/documentation/BlinkIDUX/BlinkIDClassFilter":{"fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"BlinkIDClassFilter","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/blinkidux\/blinkidclassfilter","title":"BlinkIDClassFilter","identifier":"doc:\/\/com.microblink.BlinkIDUX\/documentation\/BlinkIDUX\/BlinkIDClassFilter","type":"topic","abstract":[{"type":"text","text":"Protocol used to accept or reject classes based on country, region, and document type"}],"role":"symbol","navigatorTitle":[{"text":"BlinkIDClassFilter","kind":"identifier"}]},"doc://com.microblink.BlinkIDUX/documentation/BlinkIDUX/CaptureActivity":{"abstract":[{"type":"text","text":"An enumeration that defines the activity states the capture service supports."}],"type":"topic","url":"\/documentation\/blinkidux\/captureactivity","identifier":"doc:\/\/com.microblink.BlinkIDUX\/documentation\/BlinkIDUX\/CaptureActivity","role":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"CaptureActivity","kind":"identifier"}],"title":"CaptureActivity","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"CaptureActivity"}]},"doc://com.microblink.BlinkIDUX/documentation/BlinkIDUX/SampleBuffer":{"identifier":"doc:\/\/com.microblink.BlinkIDUX\/documentation\/BlinkIDUX\/SampleBuffer","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SampleBuffer"}],"url":"\/documentation\/blinkidux\/samplebuffer","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SampleBuffer"}],"role":"symbol","abstract":[{"text":"Wrapped non Sendable ","type":"text"},{"type":"codeVoice","code":"CMSampleBuffer"}],"title":"SampleBuffer"},"doc://com.microblink.BlinkIDUX/documentation/BlinkIDUX/MicroblinkColor":{"abstract":[],"role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"MicroblinkColor","kind":"identifier"}],"navigatorTitle":[{"text":"MicroblinkColor","kind":"identifier"}],"url":"\/documentation\/blinkidux\/microblinkcolor","type":"topic","kind":"symbol","title":"MicroblinkColor","identifier":"doc:\/\/com.microblink.BlinkIDUX\/documentation\/BlinkIDUX\/MicroblinkColor"},"doc://com.microblink.BlinkIDUX/documentation/BlinkIDUX":{"type":"topic","abstract":[],"role":"collection","identifier":"doc:\/\/com.microblink.BlinkIDUX\/documentation\/BlinkIDUX","title":"BlinkIDUX","url":"\/documentation\/blinkidux","kind":"symbol"},"doc://com.microblink.BlinkIDUX/documentation/BlinkIDUX/DocumentSide":{"identifier":"doc:\/\/com.microblink.BlinkIDUX\/documentation\/BlinkIDUX\/DocumentSide","kind":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"DocumentSide","kind":"identifier"}],"navigatorTitle":[{"text":"DocumentSide","kind":"identifier"}],"role":"symbol","type":"topic","url":"\/documentation\/blinkidux\/documentside","title":"DocumentSide","abstract":[{"type":"text","text":"Represents different sides of a document during the scanning process."}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/topicSections","op":"replace","value":[{"anchor":"Variables","title":"Variables","generated":true,"identifiers":["doc:\/\/com.microblink.BlinkIDUX\/documentation\/BlinkIDUX\/BlinkIDUXVersionNumber","doc:\/\/com.microblink.BlinkIDUX\/documentation\/BlinkIDUX\/BlinkIDUXVersionString"]}]},{"path":"\/relationshipsSections","value":null,"op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null}],"traits":[{"interfaceLanguage":"occ"}]}]}